### ISSUE TITLE
android_view_Surface.cpp

### ISSUE THREAD

**Issue by blerfont** [SuperOSR/android_frameworks_base#1]
frameworks/base/core/jni/android_view_Surface.cpp: In function 'jint android::nativeSetDisplayParameter(JNIEnv*, jclass, jobject, jint, jint, jint, jint)':
frameworks/base/core/jni/android_view_Surface.cpp:357:12: error: incomplete type 'android::SurfaceComposerClient' used in nested name specifier
frameworks/base/core/jni/android_view_Surface.cpp:358:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: some warnings being treated as errors

**Comment by podxboq** [comment]
Resuelto:
https://github.com/SuperOSR/android_frameworks_base/commit/4a92beb807448059b46f400d50bd2ecc42372972
